<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(['AppBundle\\Controller\\AccountController:connecAction' => function () {
    return ${($_ = isset($this->services['service_locator.nyanrxa']) ? $this->services['service_locator.nyanrxa'] : $this->load('getServiceLocator_NyanrxaService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\AccountController:inscriptionProfesseurAction' => function () {
    return ${($_ = isset($this->services['service_locator.xbpz3gw']) ? $this->services['service_locator.xbpz3gw'] : $this->load('getServiceLocator_Xbpz3gwService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\AccountController:modifEtudiantAction' => function () {
    return ${($_ = isset($this->services['service_locator.j_4ngww']) ? $this->services['service_locator.j_4ngww'] : $this->load('getServiceLocator_J4ngwwService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\AccountController:modifProfAction' => function () {
    return ${($_ = isset($this->services['service_locator.zinzvst']) ? $this->services['service_locator.zinzvst'] : $this->load('getServiceLocator_ZinzvstService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\AccountController:registerAction' => function () {
    return ${($_ = isset($this->services['service_locator.waepiry']) ? $this->services['service_locator.waepiry'] : $this->load('getServiceLocator_WaepiryService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\AccountController:validEtudiantAction' => function () {
    return ${($_ = isset($this->services['service_locator.j_4ngww']) ? $this->services['service_locator.j_4ngww'] : $this->load('getServiceLocator_J4ngwwService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\EleveController:creer_stage' => function () {
    return ${($_ = isset($this->services['service_locator.uzjxtgj']) ? $this->services['service_locator.uzjxtgj'] : $this->load('getServiceLocator_UzjxtgjService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\EleveController:creer_stage_traitement' => function () {
    return ${($_ = isset($this->services['service_locator.uzjxtgj']) ? $this->services['service_locator.uzjxtgj'] : $this->load('getServiceLocator_UzjxtgjService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\EleveController:info_stage' => function () {
    return ${($_ = isset($this->services['service_locator.uzjxtgj']) ? $this->services['service_locator.uzjxtgj'] : $this->load('getServiceLocator_UzjxtgjService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\IndexController:homeAction' => function () {
    return ${($_ = isset($this->services['service_locator.wcychwb']) ? $this->services['service_locator.wcychwb'] : $this->load('getServiceLocator_WcychwbService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ProfController:info_stage_conv' => function () {
    return ${($_ = isset($this->services['service_locator.xg4nl4z']) ? $this->services['service_locator.xg4nl4z'] : $this->load('getServiceLocator_Xg4nl4zService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ProfController:supprim_entreprise' => function () {
    return ${($_ = isset($this->services['service_locator.lkuqaic']) ? $this->services['service_locator.lkuqaic'] : $this->load('getServiceLocator_LkuqaicService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ProfController:traiteconvention' => function () {
    return ${($_ = isset($this->services['service_locator.lkuqaic']) ? $this->services['service_locator.lkuqaic'] : $this->load('getServiceLocator_LkuqaicService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\AccountController::connecAction' => function () {
    return ${($_ = isset($this->services['service_locator.nyanrxa']) ? $this->services['service_locator.nyanrxa'] : $this->load('getServiceLocator_NyanrxaService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\AccountController::inscriptionProfesseurAction' => function () {
    return ${($_ = isset($this->services['service_locator.xbpz3gw']) ? $this->services['service_locator.xbpz3gw'] : $this->load('getServiceLocator_Xbpz3gwService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\AccountController::modifEtudiantAction' => function () {
    return ${($_ = isset($this->services['service_locator.j_4ngww']) ? $this->services['service_locator.j_4ngww'] : $this->load('getServiceLocator_J4ngwwService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\AccountController::modifProfAction' => function () {
    return ${($_ = isset($this->services['service_locator.zinzvst']) ? $this->services['service_locator.zinzvst'] : $this->load('getServiceLocator_ZinzvstService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\AccountController::registerAction' => function () {
    return ${($_ = isset($this->services['service_locator.waepiry']) ? $this->services['service_locator.waepiry'] : $this->load('getServiceLocator_WaepiryService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\AccountController::validEtudiantAction' => function () {
    return ${($_ = isset($this->services['service_locator.j_4ngww']) ? $this->services['service_locator.j_4ngww'] : $this->load('getServiceLocator_J4ngwwService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\EleveController::creer_stage' => function () {
    return ${($_ = isset($this->services['service_locator.uzjxtgj']) ? $this->services['service_locator.uzjxtgj'] : $this->load('getServiceLocator_UzjxtgjService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\EleveController::creer_stage_traitement' => function () {
    return ${($_ = isset($this->services['service_locator.uzjxtgj']) ? $this->services['service_locator.uzjxtgj'] : $this->load('getServiceLocator_UzjxtgjService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\EleveController::info_stage' => function () {
    return ${($_ = isset($this->services['service_locator.uzjxtgj']) ? $this->services['service_locator.uzjxtgj'] : $this->load('getServiceLocator_UzjxtgjService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\IndexController::homeAction' => function () {
    return ${($_ = isset($this->services['service_locator.wcychwb']) ? $this->services['service_locator.wcychwb'] : $this->load('getServiceLocator_WcychwbService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ProfController::info_stage_conv' => function () {
    return ${($_ = isset($this->services['service_locator.xg4nl4z']) ? $this->services['service_locator.xg4nl4z'] : $this->load('getServiceLocator_Xg4nl4zService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ProfController::supprim_entreprise' => function () {
    return ${($_ = isset($this->services['service_locator.lkuqaic']) ? $this->services['service_locator.lkuqaic'] : $this->load('getServiceLocator_LkuqaicService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ProfController::traiteconvention' => function () {
    return ${($_ = isset($this->services['service_locator.lkuqaic']) ? $this->services['service_locator.lkuqaic'] : $this->load('getServiceLocator_LkuqaicService.php')) && false ?: '_'};
}]));
