<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.captcha_handler' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/Service/CaptchaHandler.php';

return $this->services['app.captcha_handler'] = new \AppBundle\Service\CaptchaHandler('6LeL0poUAAAAAH7IYXJM-tTicTsmyIlAsHX6rWJe');
