<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Security\User\UserProvider' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/UserProviderInterface.php';
include_once $this->targetDirs[3].'/src/AppBundle/Security/User/UserProvider.php';

return $this->services['AppBundle\\Security\\User\\UserProvider'] = new \AppBundle\Security\User\UserProvider();
