<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Service\ProfessorHandler' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/Service/ProfessorHandler.php';
include_once $this->targetDirs[3].'/src/AppBundle/DAO/iDAO.php';
include_once $this->targetDirs[3].'/src/AppBundle/DAO/DAOProfesseur.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Encoder/PasswordEncoderInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Encoder/BasePasswordEncoder.php';
include_once $this->targetDirs[3].'/src/AppBundle/Service/PasswordEncoder.php';

return $this->services['AppBundle\\Service\\ProfessorHandler'] = new \AppBundle\Service\ProfessorHandler(new \AppBundle\DAO\DAOProfesseur(), ${($_ = isset($this->services['app.password_encoder']) ? $this->services['app.password_encoder'] : ($this->services['app.password_encoder'] = new \AppBundle\Service\PasswordEncoder())) && false ?: '_'}, ${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())) && false ?: '_'}, ${($_ = isset($this->services['security.helper']) ? $this->services['security.helper'] : $this->load('getSecurity_HelperService.php')) && false ?: '_'});
