<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Form\SignupStudiantType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/AbstractType.php';
include_once $this->targetDirs[3].'/src/AppBundle/Form/SignupUserType.php';
include_once $this->targetDirs[3].'/src/AppBundle/Form/SignupStudiantType.php';

return $this->services['AppBundle\\Form\\SignupStudiantType'] = new \AppBundle\Form\SignupStudiantType();
