<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXahlloz\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXahlloz/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXahlloz.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXahlloz\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXahlloz\appDevDebugProjectContainer([
    'container.build_hash' => 'Xahlloz',
    'container.build_id' => 'e1ed5b85',
    'container.build_time' => 1557213326,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXahlloz');
